version: "3.9"

services:

  mongodb:
    image: mongo:7
    container_name: recruitment-mongodb
    restart: always
    env_file:
      - .env.example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - recruitment-network

  app:
    build: .
    container_name: recruitment-app
    restart: always
    env_file:
      - .env.example
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - recruitment-network

volumes:
  mongo-data:

networks:
  recruitment-network:
    driver: bridge
